from pathlib import Path
from typing import Any
from typing import Callable
from typing import TypeAlias
from typing import TypeVar

T = TypeVar("T")

def load_yaml(resource_name: str, parent_location: Path | None, *args, **kwargs) -> NavigableDict: ...
def load_csv(resource_name: str, parent_location: Path | None, *args, **kwargs) -> list[list[str]]: ...
def get_resource_location(parent_location: Path | None, in_dir: str | None) -> Path: ...
def expand_env_vars(value: str) -> str: ...

class NavigableDict(dict):
    def __init__(
        self,
        head: dict | None = ...,
        label: str | None = ...,
        _filename: str | Path | None = ...,
    ): ...
    @staticmethod
    def from_yaml_file(filename: str | Path | None = ...) -> NavigableDict: ...
    @staticmethod
    def from_yaml_string(yaml_content: str | None = None, label: str | None = None) -> NavigableDict: ...
    @staticmethod
    def from_dict(my_dict: dict, label: str | None = None) -> NavigableDict: ...
    def to_yaml_file(
        self, filename: str | Path | None = ..., header: str | None = ..., top_level_group: str | None = ...
    ) -> None: ...
    def get_private_attribute(self, key: str) -> Any: ...
    def set_private_attribute(self, key: str, value: Any) -> None: ...
    def has_private_attribute(self, key: str) -> bool: ...
    def get_label(self) -> str | None: ...
    def set_label(self, value: str) -> None: ...
    def get_raw_value(self, key: str) -> Any: ...
    def add(self, key: str, value: Any) -> None: ...
    def clear(self) -> None: ...
    def set_alias_hook(self, hook: Callable[[str], str]) -> None: ...
    def get_memoized_keys(self) -> list[str]: ...
    def del_memoized_key(self, key: str) -> bool: ...
    def get_filename(self) -> str | None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __dir__(self) -> list[str]: ...
    def as_typed(self, schema_type: type[T]) -> T: ...

navdict: TypeAlias = NavigableDict
NavDict: TypeAlias = NavigableDict
